# Generated by Django 3.1.3 on 2020-11-26 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=50)),
                ('pm', models.CharField(max_length=50)),
            ],
        ),
    ]
