# Generated by Django 2.2.8 on 2020-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wh',
            name='pm',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
